version: '3.8'

services:
  # 1. Database Vektor (Qdrant)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: legal_qdrant
    ports:
      - "6333:6333" # API HTTP
      - "6334:6334" # gRPC (Opsional, sangat cepat untuk komunikasi internal)
    volumes:
      - qdrant_storage:/qdrant/storage

  # 2. Database Relasional & Memori Sesi LangGraph (PostgreSQL)
  postgres:
    image: postgres:16-alpine
    container_name: legal_postgres
    environment:
      POSTGRES_USER: legal_admin
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: legal_assistant_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

   # 3. Application Server / Entrypoint API [BARU DI SINI]
  app_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legal_app_entrypoint
    ports:
      - "8000:8000"
    env_file:
      - .env # Mengambil rahasia API Key Gemini secara aman dari file .env lokal server
    depends_on:
      - postgres
      - qdrant

volumes:
  qdrant_storage:
  postgres_data:
